from app.models import user
from app.models import game
from app.models import requirement
from app.models import favorite
from app.models import user_scan
from app.models import admin
from app.models import cpu
from app.models import gpu
from app.models import ram
from app.models import storage
from app.models import activity
from app.models import chat
from app.models import cart
from app.models import order
from app.models import purchase
from app.models import community